import Header from "@/components/Header/Header";
import { supabase } from "@/lib/supabase-server/supabase";
import { GeistSans } from "geist/font/sans";
import type { Metadata } from "next";
import { Toaster } from "sonner";
import "./globals.css";
import Providers from "./providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const { data } = await supabase.auth.getUser();
  return (
    <html lang="en">
      <body className={GeistSans.className}>
        <Providers>
          <div className="flex min-h-screen flex-col">
            <Header user={null} />
            {children}
          </div>
          <Toaster />
        </Providers>
      </body>
    </html>
  );
}
